### ISSUE TITLE
Revisión de carpetas

### ISSUE THREAD

**Issue by angelicasoma** [verito-alanis/Equipo02#6]
- [ ] incluir el htm de la sección convivir
- [ ] Corregir la fotografía de lily por una que se vea solo la cara y ajuste de tamaño
- [ ] linkear el botón de adopta a su pagina.

**Comment by angelicasoma** [comment]
- [ ] crear uan carpeta indibudual para las imágenes de la ultima pagina, 
- [ ] que todos los java estén dentro de una sola carpeta 
- [ ]

**Comment by jambdeep** [comment]
Muchas gracias por atender la solicitud pero recuerda hacerlo en el mismo hilo #3 @angelicasoma
