### ISSUE TITLE
Tamaño conveniente de la imágenes

### ISSUE THREAD

**Issue by JorgeMauricio-USB** [verito-alanis/Equipo02#7]
- [ ] 31.25 rem x  31.25 rem (500 px X 500px) para las imágenes de perritos dentro de suaves lomitos
- [ ] 20 rem x 20 rem (320x320px) para las imágenes de perritos en casos de éxito
- [ ] 146.25 rem x 37.5 rem (2340 px X 500px)para las imágenes banner (grandes) 
No olvidar que se hizo previamente (font-size: 62.5% para normalizar)

**Comment by jambdeep** [comment]
Recuerda hacer los comentarios en el mismo hilo #5 @JorgeMauricio-USB
